apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: api-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: pgpass
                  optional: false